insta_acconts_python = [
    {'name': 'programwith.fun', 'url': 'https://www.instagram.com/programwith.fun/'},
    {'name': 'python.joy', 'url': 'https://www.instagram.com/python.joy/'},
    {'name': 'oficinapython', 'url': 'https://www.instagram.com/oficinapython/'},
    {'name': 'pythonacademybr', 'url': 'https://www.instagram.com/pythonacademybr/'},
    {'name': 'lucid.programmer', 'url': 'https://www.instagram.com/lucid.programmer/'},
    {'name': '_tancodes_', 'url': 'https://www.instagram.com/_tancodes_/'},
    {'name': 'pycodebr', 'url': 'https://www.instagram.com/pycodebr/'},
    {'name': 'python_cheatbook', 'url': 'https://www.instagram.com/python_cheatbook/'},
    {'name': 'coderz.py', 'url': 'https://www.instagram.com/coderz.py/'},
    {'name': 'python.science', 'url': 'https://www.instagram.com/python.science/'},
    {'name': 'lamagadepython', 'url': 'https://www.instagram.com/lamagadepython/'},
    {'name': 'python.coder_', 'url': 'https://www.instagram.com/python.coder_/'},
    {'name': 'backup_python.dev', 'url': 'https://www.instagram.com/backup_python.dev/'},
    {'name': 'python_programming_snippets', 'url': 'https://www.instagram.com/python_programming_snippets/'},
    {'name': 'python___developers', 'url': 'https://www.instagram.com/python___developers/'},
    {'name': 'dynamic.coding', 'url': 'https://www.instagram.com/dynamic.coding/'},
    {'name': 'flask_python', 'url': 'https://www.instagram.com/flask_python/'},
    {'name': 'python.web', 'url': 'https://www.instagram.com/python.web/'},
    {'name': 'itchallenges', 'url': 'https://www.instagram.com/itchallenges/'},
    {'name': 'dark.coding', 'url': 'https://www.instagram.com/dark.coding/'},
    {'name': 'azurewill', 'url': 'https://www.instagram.com/azurewill/'},
    {'name': 'i_know_python', 'url': 'https://www.instagram.com/i_know_python/'},
    {'name': 'finxterdotcom', 'url': 'https://www.instagram.com/finxterdotcom/'},
    {'name': 'python.hunt', 'url': 'https://www.instagram.com/python.hunt/'},
    {'name': 'the.pythondev', 'url': 'https://www.instagram.com/the.pythondev/'},
    {'name': 'jjean_dev', 'url': 'https://www.instagram.com/jjean_dev/'},
    {'name': 'inside_python', 'url': 'https://www.instagram.com/inside_python/'},
    {'name': 'python.advance.projects', 'url': 'https://www.instagram.com/python.advance.projects/'},
    {'name': 'learn.analytics', 'url': 'https://www.instagram.com/learn.analytics/'},
    {'name': 'amazing_python3', 'url': 'https://www.instagram.com/amazing_python3/'},
    {'name': 'coders.eduyear', 'url': 'https://www.instagram.com/coders.eduyear/'},
    {'name': 'pcondemandotcom', 'url': 'https://www.instagram.com/pcondemandotcom/'},
    {'name': 'python_scripts', 'url': 'https://www.instagram.com/python_scripts/'},
    {'name': 'python.hub', 'url': 'https://www.instagram.com/python.hub/'},
    {'name': 'papa_programmer', 'url': 'https://www.instagram.com/papa_programmer/'},
    {'name': 'pythonizando', 'url': 'https://www.instagram.com/pythonizando/'},
]

dicas_python = [
    {'dica': 'Converter para PDF', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_dicapython-python-dica-activity-6773560821525082112-uQpq'},
    {'dica': 'Fontes Artísticas', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_dicapython-python-dica-activity-6773201535049506816-kpZi'},
    {'dica': 'Gerador de textos fictícios', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_dicapython-python-dica-activity-6772892495647961090-0Q5m'},
    {'dica': 'Gerador de mapas de cidades brasileiras com Python', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_mapa-maps-dicapython-activity-6772639591842271232-ZYON'},
    {'dica': 'Encurtador de url', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_dicapython-python-dica-activity-6772465636548362240-KPv_'},
    {'dica': 'Notificações', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_dicapython-python-dica-activity-6772103877006295041-R6tr'},
    {'dica': 'csv', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_csv-dicapython-python-activity-6771025045063053312-W0jH'},
    {'dica': 'Baixar Videos', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_youtube-dicapython-python-activity-6770657904660951040-MfxA'},
    {'dica': 'Traduzir textos', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_traduzir-dicapython-python-activity-6770294228577783808-T-ov'},
    {'dica': 'Capturando IP', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_redes-host-ip-activity-6769928663094870016-Cp2F'},
    {'dica': 'Gerador de senhas', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_gerador-senhas-password-activity-6769570939303723008-nA_d'},
    {'dica': 'Barra de Progresso', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_progresso-dicapython-python-activity-6768486191579877377-CoUR'},
    {'dica': 'Matplotlib', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_matplotlib-analisededados-dicapython-activity-6768138708920139776-mc9l'},
    {'dica': 'PyInputPlus', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_dicapython-python-dica-activity-6767757480329039872-rsmr'},
    {'dica': 'String', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_dicapython-python-dica-activity-6767399650912718848-hPyw'},
    {'dica': 'F-Strings', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_python-github-dicas-activity-6765955089313132544-IZct'},
    {'dica': 'Tratamento de Imagens com Pillow', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_imagem-pillow-github-activity-6765587261707882496-stVN'},
    {'dica': 'BeautifulSoup', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_google-python-requests-activity-6765230617769648128-Vuon'},
    {'dica': 'Selenium', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_selenium-python-automatizaaexaeto-activity-6764952352987385856-nabR'},
    {'dica': 'List Comprehension', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_python-dica-github-activity-6764580845379428352-qkvt'},
    {'dica': 'Django', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_python-django-login-activity-6763863831056846848-2UoB'},
    {'dica': 'Wikipédia', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_python-dica-programador-activity-6763506204690939904-8Aih'},
    {'dica': 'Desinstalar Pacotes', 'url': 'https://www.linkedin.com/posts/ericksonlopesdev_python-dica-programador-activity-6761352470196219904-5Lli'},
]